name: Deploy FRONTEND to PRODUCTION

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      # Checkout репозитория
      #----------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      #----------------------------------------------
      # Установка Node.js 24
      #----------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      #----------------------------------------------
      # Установка зависимостей
      #----------------------------------------------
      - name: Install dependencies
        run: npm ci


      #----------------------------------------------
      # Сборка React приложения
      #----------------------------------------------
      - name: Debug env
        run: |
          echo "USER: $REACT_APP_USER_SERVICE_BASE_URL"
          echo "PRODUCT: $REACT_APP_PRODUCT_SERVICE_BASE_URL"
          echo "PRICING: $REACT_APP_PRICING_ENGINE_BASE_URL"
        env:
          REACT_APP_USER_SERVICE_BASE_URL: ${{ secrets.REACT_APP_USER_SERVICE_BASE_URL }}
          REACT_APP_PRODUCT_SERVICE_BASE_URL: ${{ secrets.REACT_APP_PRODUCT_SERVICE_BASE_URL }}
          REACT_APP_PRICING_ENGINE_BASE_URL: ${{ secrets.REACT_APP_PRICING_ENGINE_BASE_URL }}

      - name: Build project
        run: CI=false npm run build
        env:
          REACT_APP_USER_SERVICE_BASE_URL: ${{ secrets.REACT_APP_USER_SERVICE_BASE_URL }}
          REACT_APP_PRODUCT_SERVICE_BASE_URL: ${{ secrets.REACT_APP_PRODUCT_SERVICE_BASE_URL }}
          REACT_APP_PRICING_ENGINE_BASE_URL: ${{ secrets.REACT_APP_PRICING_ENGINE_BASE_URL }}
      #----------------------------------------------
      # Очистка директории на сервере
      #----------------------------------------------
      - name: Prepare server directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo rm -rf /var/www/FRONTEND_MARKET_WEB
            sudo mkdir -p /var/www/FRONTEND_MARKET_WEB
            sudo chown -R $USER:$USER /var/www/FRONTEND_MARKET_WEB

      #----------------------------------------------
      # Копирование build на сервер
      #----------------------------------------------
      - name: Upload build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "build/*"
          target: "/var/www/FRONTEND_MARKET_WEB"